### ISSUE TITLE
Mapping Method of an attribute form

### ISSUE THREAD

**Issue by DanDavies1989** [MicroStrategy/mstrio-py#103]
Hey 

Is it possible to get the mapping method of an attribute form please?
We are having issues preventing us from using MicroStrategy Workstation due to any edits of an attribute changing the mapping method (only really visible using MicroStrategy Developer) from Manual to Automatic 
We cannot use Automatic with our Data Warehouse as there are instances where we need to split things out and Automatic will create all manner of headaches for us 
Ideally we need this sorted in Workstation but equally it would be nice to build a script around checking for cases that have been changed in error

**Comment by urszulajaczewska** [comment]
Hi @DanDavies1989, unfortunately we don't have possibility to implement this as we don't have endpoints to read or update mapping method for attributes.

**Comment by DanDavies1989** [comment]
No problem
Is this something that could be considered for a future enhancement? I would expect this issue to be affecting many customers not just us.

**Comment by apiotrowskiMicroStrategy** [comment]
Hi @DanDavies1989 

We are constantly trying to improve already existing solutions and your suggestion seems relevant. However this is not yet on our backlog as we have some other priorities to deliver.

I can however assure you that we prioritize the work based on customer and market needs and will monitor for interest in this one as well.
