### ISSUE TITLE
Possible to create and manage subscription Dynamic Recipient Lists?

### ISSUE THREAD

**Issue by hustontrevor** [MicroStrategy/mstrio-py#109]
I'd like to stay in Python converting Narrowcast services to iServer subscriptions, but I'm not seeing any way to create Dynamic Recipient Lists for my subscriptions. 

It would be similar to this class from WebSDK
https://www2.microstrategy.com/producthelp/Current/ReferenceFiles/reference/com/microstrategy/web/objects/WebSubscriptionDynamicRecipientList.html

**Comment by urszulajaczewska** [comment]
Hi @hustontrevor, we'll investigate possibility of implementing managing subscription Dynamic Recipient Lists. If there are any updates, we'll let you know.

**Comment by urszulajaczewska** [comment]
Hi @hustontrevor, Dynamic Recipient Lists are now available with 11.3.9.101 version.
