### ISSUE TITLE
executing a datamart report to push data to db

### ISSUE THREAD

**Issue by nadavneu** [MicroStrategy/mstrio-py#115]
hi @apiotrowskiMicroStrategy , 

2021u7 exposed several new DataMart report options , but is it possible that the basic feature to execute DM report is actually still not GA?  
1. if this is indeed the case , please take under consideration that a report is created once (usually manually), but used 1000X times , seems strange that the creation and the update of such report are exposed but the actual execution isn't, and  i believe it should be prioritized asap , since it renders the report as almost useless.
2. the main automation and usage for admin processes is more for the execution rather than the creation.  
3. as a workaround - 
i tried running my DM report as a normal report from the mstrio-python , and it behaved as a normal report , the DM was not created, i was using: 
### repId = the id of the DM report
 rp = mstrio.project_objects.Report(connection=conn, id=repId)
   js = rp.to_dataframe()

4.  another workaround i thought of , is creating an event based dedicated subscription for that DM report , and raise the event , but it will be an async process , where i have to constantly ping the service and make sure when DM report is done , and makes the managment more complex .

5. maybe i'm missing something and there is a very simple solution i'm overlooking
 
Best Regards (and keep those updates going , seems like team is working hard on api),
Nadav

**Comment by urszulajaczewska** [comment]
Hi @nadavneu, mstrio does not support DataMart reports. However, it's possible that there are endpoints for creating and editing DataMart reports but there are no endpoints for execution yet.

**Comment by nadavneu** [comment]
thanks, 
MSTR REST API already exposed these options 2 months ago as i mentioned above, usually mstrio-py implementation is close by after that  (https://microstrategy.github.io/rest-api-docs/common-workflows/manage-datamart-objects/)

i bring this into discussion as the exposed option is almost useless (while comparing # of executions vs creations of datamarts ),  and this feature is very much required and waited for (also  command/system manager don't have a straight forward execution).

mstrio designed to assist adminitrators (amonth others) to better automate processes , and the execution of such datamart option is oh so needed . 

appreciate you taking the time to respond !!
