### ISSUE TITLE
Create User with NTLINK parameter

### ISSUE THREAD

**Issue by ismailmuller** [MicroStrategy/mstrio-py#119]
In Microstrategy Command Manager, it's possible to create user with NTLINK param (Windows Authentication).
This is used for Kerberos Authetication (and is different from LDAP).
Is this feature planned to be added ?
Thanks

**Comment by mgorskiMicroStrategy** [comment]
Hi, currently user with NTLINK param is not on the roadmap. Can you describe why you need this functionality, maybe we can think about adding it?
