### ISSUE TITLE
cannot authenticate when MSTR instance is configured to use SAML

### ISSUE THREAD

**Issue by dstandish** [MicroStrategy/mstrio-py#12]
My company uses SAML auth for its MSTR instance.  We would like to use the api to trigger cube refresh.  Is there any way to do this?  It seems there is no way to authorize the api when saml is enabled.

**Comment by mwellbro** [comment]
I second this, as far as I´ve seen only "Standard" and "LDAP" are currently implemented - seeing as the MicroStrategy Library can work with SAML it would be great to see this work with mstrio / mstrio-py.

**Comment by OskarDuda** [comment]
Hi @mwellbro , @dstandish we have currently created work items to include these in our workflow. We're doing the best we can to deliver all features requested by our users, but SAML support is not currently at the top of our priorities list and it will take some time before we implement it.

**Comment by urszulajaczewska** [comment]
Hi @mwellbro @dstandish, as for the update, we don't have plans for SAML implementation at the moment, because it's not our top priority. We'll come back with more updates if something changes.

**Comment by dstandish** [comment]
I don't use MSTR anymore so it's not an issue for me personally.  However if I remember correctly the isssue was that there was apparently no way to authenticate to the API when saml was enabled.  Enabling SAML essentially disabled the API.

**Comment by pawelgnatowski** [comment]
This solution will not make it fully automated with M2FA enabled, but does work in general.
https://www.pablo-labs.com/post/can-python-saml-with-multifactor-authentication-and-mstr-io-api-work-together

**Comment by XiaokunHou** [comment]
Why use a dedicated API user which is not using SAML auth mode to do backend automation?

SAML usually requires a user's interaction to verify you are actually you are, it works with browsers. If you want to embed this into your front end, definitely it works. Can refer to this https://www.youtube.com/watch?v=6TTy0nDksWw&ab_channel=HarryonMicroStrategy
If for backend automation, should do to another auth mode :)
