### ISSUE TITLE
LogicalTable Alter is_logical_size_locked not working

### ISSUE THREAD

**Issue by Vickoh** [MicroStrategy/mstrio-py#122]
LogicalTable(connection=conn, id="ID",project_id=conn.project_id).alter(is_logical_size_locked=True)

Fix On logical_table.py:

Change: is_logical_size_locked: Optional[str] = None
To: is_logical_size_locked: Optional[bool] = None,

On  _API_PATCH add  is_logical_size_locked:
  _API_PATCH: dict = {
        (
            "name",
            "description",
            "logical_size",
            "is_logical_size_locked",
            "is_true_key",
            "primary_data_source",
            "enclose_sql_in_parentheses",
            "physical_table",
            "secondary_data_sources",
        ): (tables_api.patch_table, "partial_put"),
        "folder_id": (objects.update_object, "partial_put"),
    }

**Comment by urszulajaczewska** [comment]
@Vickoh fix is now available with new 11.3.9.103 release.
