### ISSUE TITLE
Need ability to interact with User NTLink

### ISSUE THREAD

**Issue by hustontrevor** [MicroStrategy/mstrio-py#125]
https://github.com/MicroStrategy/mstrio-py/blob/f63a1193b25a876b6621e919987f9a678e6a1fdb/mstrio/users_and_groups/user.py

We use Kerberos Authentication NTLink in our Dev environment to grant SSO access to Developer.  In all environments we use LDAP for web access.  
In an effort to ensure the GUIDS match across environments, users are now only able to be automatically created in Prod via LDAP.  

If any users are created or modified in Prod, I have implemented a mstrio package process to pull them from Prod and import them to Dev.  Once in Dev, they may be granted access to more User Groups and may be allowed to use Developer via the NTLink property.  

If they are later modified in Prod, then packaged to Dev, they will lose these extra settings.  

I was able to successfully capture existing User Group membership before the package is applied then re-add those groups after the packaging.  

HOWEVER, I cannot see or set the NTLink property of a user.  So this property is just lost/overwritten during the down packaging.  

Please let me know how I might solve this problem, or if there is a plan to expose NTLink in a soon to be released version.

**Comment by urszulajaczewska** [comment]
Hi @hustontrevor, currently we don't support NTLink property and this feature is not on the roadmap. However, we will review this and if there any changes to the roadmap regarding NTLink, we will update this issue.

**Comment by urszulajaczewska** [comment]
@hustontrevor As we don't have this in our roadmap, please log Enhancement Request to MSTR support if you find this issue necessary. It will help us prioritize our roadmap.
