### ISSUE TITLE
Need a way to pull the sqlView for a report

### ISSUE THREAD

**Issue by hustontrevor** [MicroStrategy/mstrio-py#126]
Looks like it exists in REST but I don't see the same in MSTRIO 

/api/v2/reports/{reportId}/instances/{instanceId}/sqlView

**Comment by urszulajaczewska** [comment]
Hi @hustontrevor, we'll add this enhancement to the Report module which is currently scheduled to be delivered with 2023 December release.

**Comment by urszulajaczewska** [comment]
@hustontrevor Report module has been moved to be released in Q3 of 2024, possibly earlier. We're sorry for the inconvenience and thank you for your patience.

**Comment by apiotrowskiMicroStrategy** [comment]
It's available under `Report.sql` property. Closing
