### ISSUE TITLE
How To Create Threshold based alert subscriptions

### ISSUE THREAD

**Issue by JTanner4** [MicroStrategy/mstrio-py#130]
I want to create a threshold based email alert subscription via the api that will only send an email at the designated time if the conditions of the threshold in a report are met as described in this [article](https://community.microstrategy.com/s/article/Setting-up-Data-Alerts-with-MicroStrategy?language=en_US).

Is this currently possible using mstrio or the api? I see that there is a `create_subscription()` function, but am not seeing anywhere that I can specify that I want to set an alert threshold on the subscription.

**Comment by urszulajaczewska** [comment]
Hi @JTanner4, you can create subscriptions via api/mstrio and reports with thresholds via api, but possibility to create email alert threshold is currently only available in Web.

**Comment by urszulajaczewska** [comment]
@JTanner4 As we don't have this in our roadmap, please log Enhancement Request to MSTR support if you find this issue necessary.
