### ISSUE TITLE
Report Object uses String of a id Field instead of the origin Type int

### ISSUE THREAD

**Issue by mFeigeInvia** [MicroStrategy/mstrio-py#138]
I tried to request a Report from API and metrio-py and all Attributs are Strings, but the the origin type in Mstr are int 
Example:
  {'attribute_name': 'Nice ID',
   'attribute_id': '3386325344275CD575C735A2D97C9C78',
   'elements': [{'id': '3386325344275CD575C735A2D97C9C78:84',
     'formValues': ['69']},
    {'id': '3386325344275CD575C735A2D97C9C78:185', 'formValues': ['199']},

It would be better to get the type defined in Mstr

**Comment by urszulajaczewska** [comment]
Hi @mFeigeInvia, API returns ID as a string, and since mstrio-py only wraps API, we cannot change this behaviour.
