### ISSUE TITLE
Create_dataset() folderId selector disabled

### ISSUE THREAD

**Issue by YouriFC** [MicroStrategy/mstrio-py#14]
Currently, every dataset/table created by create_dataset() defaults to 'My Reports' with no way to change it. In enterprise use-cases, this has severe limitations.

Since the MSTR API [supports folderId selection ](https://demo.microstrategy.com/MicroStrategyLibrary/api-docs/index.html#!/Datasets/createDICube), is this something that can safely be added to the create_dataset method? 

It's a very minor code-change, and it worked without issues when I made the changes locally. To my knowledge, other methods are unaffected.
I can add it to my fork and make a pull request, but if there are implications I am unaware of that'd be waste of time. 

Let me know.

**Comment by drzamich** [comment]
Hello @YouriFC. Since **mstrio-py** version `11.1.4.002` you can use the `Dataset` class to export data to MicroStrategy. Simply pass the `folder_id` parameter to the `Dataset.create()` method.
