### ISSUE TITLE
Attribute Relationship Management

### ISSUE THREAD

**Issue by DStavilaNI** [MicroStrategy/mstrio-py#148]
Hey Guys,

I do have a question regarding Attribute Relationship Management. Specifically, for a given attribute, we are trying to programmatically set some children. The key for the target attribute is a form group. 

![image](https://github.com/MicroStrategy/mstrio-py/assets/35329597/06bb6261-685b-41f4-9d98-5f94acdc3c4e)

The problem happens when attempting to get the attribute relationship candidates, using the `list_relationship_candidates` attribute method:

`candidates = attr_item.list_relationship_candidates(already_used=True, to_dictionary=True)`. The method fails with the error ''NoneType' object is not iterable'.  Looking a bit through `list_relationship_candidates()` I did find this:

![image](https://github.com/MicroStrategy/mstrio-py/assets/35329597/e69fe383-37cd-49f2-b19f-35929bc46e89)

and it explains why this method fails - the attribute key, which is a form group, does not have any expressions, hence the error.

Is it a known issue ? What would be the solution in this case - should I simply avoid using this method and set directly the attribute children?

Note: It works, for the same attribute, from the Workstation, when doing it manually.

**Comment by urszulajaczewska** [comment]
Hi @DStavilaNI, we've logged the defect for this issue. I'll let you know when the fix is available.

**Comment by DStavilaNI** [comment]
Cool, thank you.

**Comment by urszulajaczewska** [comment]
Hi @DStavilaNI, fix is now available with new mstrio-py release.
