### ISSUE TITLE
list_dossiers command anomaly

### ISSUE THREAD

**Issue by kkadu** [MicroStrategy/mstrio-py#151]
I have a project where we have around 4k+ dossiers but when I run `list_dossiers(connection=conn, project_id=xxx)`, I am getting different outputs using `len(list_dossiers(connection=conn, project_id=xxx))` in each iteration.

**Comment by urszulajaczewska** [comment]
Hi @kkadu, fix for this issue will be available with 11.3.11.101 release (2023/09/28).

**Comment by mgorskiMicroStrategy** [comment]
@kkadu 11.3.11.101 release is already available.
