### ISSUE TITLE
FFSQL report query

### ISSUE THREAD

**Issue by kkadu** [MicroStrategy/mstrio-py#152]
I currently do not see a functionality or way to extract the SQL from FFSQL (Free Form SQL Report). I see a similar issue open https://github.com/MicroStrategy/mstrio-py/issues/139 but that is related to SQL that the reporting engine generates so it may or may not be related.

**Comment by urszulajaczewska** [comment]
Hi @kkadu, this functionality is planned to be released with Report module next year. Please contact Support and log an ER, which will help prioritize our backlog.

**Comment by kkadu** [comment]
@urszulajaczewska - Do you have any estimated date for the release of this feature?

**Comment by urszulajaczewska** [comment]
@kkadu This feature is planned to be released with June release.

**Comment by apiotrowskiMicroStrategy** [comment]
Feature released. Closing
