### ISSUE TITLE
Functionality to extract list of base formula in project

### ISSUE THREAD

**Issue by kkadu** [MicroStrategy/mstrio-py#153]
I could not find a functionality to get a list of all base formula's in a project using the `mstrio.modeling` package. We are trying to create a lineage for project documentations and we have base formulas created on top of facts which are used in metrics. So trying to figure out a way to list those and link then to metrics (upwards) and facts (downwards)

**Comment by urszulajaczewska** [comment]
Hi @kkadu, please log an enhancement request with a good description of your use case so we can add it to our backlog.

**Comment by magerdaniel** [comment]
@urszulajaczewska : I think this is allready doable. You can perform a search to get all objects of type 7. Using / combinig it with upward / downward full recursive dependency option.
But maybe I miss something...
