### ISSUE TITLE
relax dependency on `requests` package

### ISSUE THREAD

**Issue by elgalu** [MicroStrategy/mstrio-py#154]
https://github.com/MicroStrategy/mstrio-py/blob/c6cea33b15bcd876ded4de25138b3f5e5165cd6d/pyproject.toml#L67

could you relax the dependency on `requests` package? we need 2.31.0 but this seems blocked to <2.29 since some years for no apparent reason.

**Comment by urszulajaczewska** [comment]
Hi @elgalu, this will be available with our next release (28 September).

**Comment by elgalu** [comment]
thanks, this was fixed in mstrio-py==11.3.11.101
