### ISSUE TITLE
Is it possible to relax nbconvert to >= 6.4.5 ?

### ISSUE THREAD

**Issue by elgalu** [MicroStrategy/mstrio-py#155]
https://github.com/MicroStrategy/mstrio-py/blob/c6cea33b15bcd876ded4de25138b3f5e5165cd6d/pyproject.toml#L81

Is it possible to relax nbconvert to >= 6.4.5 ? we're currently stuck with the old version

**Comment by mgorskiMicroStrategy** [comment]
@elgalu I don't think it is easily possible. We changed it from 6.x due to security issues.
I wonder if you are using our Jupyter connector or you only use mstrio-py in Jupyter?

**Comment by elgalu** [comment]
we use both packages separately, but that's ok, we'll upgrade nbconvert then, thanks
