### ISSUE TITLE
iserver is running check?

### ISSUE THREAD

**Issue by rickymedrano** [MicroStrategy/mstrio-py#162]
Hi,

Is it possible to use mstrio to check if the intelligence server is running? 
I see the /api/monitors/iServer/nodes endpoint gives back a running status but that is for the status of the nodes, not the iServer service.

**Comment by mgorskiMicroStrategy** [comment]
Hi @rickymedrano 
At this moment it's not possible with mstrio-py. When there is a problem with intelligence server you will get error about it when using functions using its resources. 
You are right there is no endpoint to check iserver status. I know that there is possibility to check iserver status in environment provision window.
If you need this functionality in mstrio-py and have endpoint for this please log enhancement request to Support with proper description of you use case

**Comment by apiotrowskiMicroStrategy** [comment]
Required request steps provided. Closing
