### ISSUE TITLE
User's Last Access

### ISSUE THREAD

**Issue by ViniciusLevyC** [MicroStrategy/mstrio-py#164]
Hello!

Is there any way to list all users in the enviroment and show the date of the last access? If the answer is yes, how can I do that?

Thanks!

**Comment by mgorskiMicroStrategy** [comment]
@ViniciusLevyC Hi at this moment this is not possible in mstrio-py. 
Only way I see is to go to 'User Activity' dossier from 'Platform Analytics' project and there you can see user activity details. If you want to show user  last access time when listing users in mstrio-py you should log enhancement request with your use case to Support.

**Comment by ViniciusLevyC** [comment]
Thanks for your reply.
