### ISSUE TITLE
Possibility to partially replace/update cube

### ISSUE THREAD

**Issue by philthestone** [MicroStrategy/mstrio-py#166]
I am using mstrio to push a huge dataframe to MSTR. Every day 1/4 (the newest x days) of the dataset gets an update (row's are deleted, updated or added). There are different update strategies to push the data to mstr, being 'update', 'upsert', or 'replace'. The problem with 'update' and 'upsert' is, that it cannot really handle deleted rows, which is key in our application. 'Replace' is doing the job, but the problem is that it deletes all data, so every day we have to push the complete dataset to mstr again.

So optimally I would only use the update strategy 'replace' for my latest x days, and use upsert strategy for the older data. Is there a way to do this?

Or is there a possibility to smartly delete a rows of a cube by giving some attributes which have to match?

**Comment by mgorskiMicroStrategy** [comment]
Hi, @philthestone 
At this moment it seems that there is no possibility to delete rows based on some sort of qualification. It seems to be useful feature please log this as Enhancement Request to Support so we can proceed with this idea and you will be informed when your case will be solved

**Comment by apiotrowskiMicroStrategy** [comment]
Enhancement Request flow provided, no update available. Closing
