### ISSUE TITLE
Pip install

### ISSUE THREAD

**Issue by angelmapmaker** [MicroStrategy/mstrio-py#17]
Hi, 

I have problem for to insatall, 
I executed this command : pip install mstrio-py
but the console returned this err 
pip install mstrio-py

Could not fetch URL https://pypi.org/simple/mstrio-py/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mstrio-py/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))) - skipping
  ERROR: Could not find a version that satisfies the requirement mstrio-py (from versions: none)
ERROR: No matching distribution found for mstrio-py

someone can help me

**Comment by scottrigney** [comment]
@angelmapmaker I believe this is a bug with pip specifically on Python 3.6 Check out this [SO post](https://stackoverflow.com/questions/41328451/ssl-module-in-python-is-not-available-when-installing-package-with-pip3) for more details.

**Comment by saonidas7** [comment]
How you resolved this issue?
