### ISSUE TITLE
No support for changing the Metric Join Type.

### ISSUE THREAD

**Issue by vladbalcanu** [MicroStrategy/mstrio-py#171]
There is currently no way of picking a different Metric Join Type from the python API. This should not be confused with the metric formula join type which is currently a property of the Metric object and can be changed when creating/updating a Metric object. But such a parameter is not available for the Metric Join Type (the one that affects how the metric joins with the other metrics inside a report.
I also searched for an alternative but I could not find any right now inside the Python API.

**Comment by mgorskiMicroStrategy** [comment]
@vladbalcanu in metric VLDB settings there is 'Metric Join Type'.
You can check current value and possible options this way: `print(metric_obj.vldb_settings['Metric Join Type'])`
and alter this way: `metric_obj.alter_vldb_settings(names_to_values={'Metric Join Type':<SETTING VALUE>})`

**Comment by apiotrowskiMicroStrategy** [comment]
Workflow provided. Closing
