### ISSUE TITLE
is_dossier function is called in is_document function

### ISSUE THREAD

**Issue by hdesobry** [MicroStrategy/mstrio-py#185]
Hello,

I get a deprecation warning when I use the is_document function. The function calls the is_dossier function that trigger a deprecation warning. The is_document function should be updated to use the is_dashboard function.

https://github.com/MicroStrategy/mstrio-py/blob/02628a945ca638958de11acd29a105131a54e818/mstrio/utils/helper.py#L1126

**Comment by mgorskiMicroStrategy** [comment]
Hi @hdesobry 
Thanks for catching it, we will fix it with next June release

**Comment by apiotrowskiMicroStrategy** [comment]
Issue should be resolved, closing
