### ISSUE TITLE
full_search object_types validate_enum_val fails with list of int values

### ISSUE THREAD

**Issue by hustontrevor** [MicroStrategy/mstrio-py#189]
`full_search(connection=conn,project=project_id,object_types=[3,55])`

object_types(enum class object or **integer** or **list of** enum class objects
            or **integers**): Type(s) of object(s) to be searched, such as
            Folder, Attribute or User. Possible values available in ENUMs
            mstrio.types.ObjectTypes and mstrio.types.ObjectSubTypes

`Incorrect enum value '55'. Possible values are [[1, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 20, 21, 26, 28, 29, 30, 31, 32, 34, 35, 36, 39, 43, 44, 45, 47, 49, 50, 51, 53, 55, 56, 57, 58, 67, 68, 84, None], [256, 768, 769, 770, 774, 776, 777, 778, 779, 781, 2816, 8704, 8705, 9984, 10752, 14081, 14848, 3072, 3075, 5376, 3076, 3073, 3074, 11009, None]]`

The single quotes around the enum value are misleading.  I was trying to figure out how my int became a str.

The true problem appears to be that it's comparing a single int value to a list of lists of ints. 

mstrio-py==11.4.3.101

**Comment by apiotrowskiMicroStrategy** [comment]
Hi @hustontrevor 

We'll look into this issue and I'll get back to you with an update, when ready.

**Comment by apiotrowskiMicroStrategy** [comment]
The solution has been applied in already released version so the issue should be resolved
