### ISSUE TITLE
alter subscription | prompt instance id must be provided

### ISSUE THREAD

**Issue by nxlsschxnk** [MicroStrategy/mstrio-py#197]
When I want to alter a subscription, I have to provide a Prompt Instance Id.

Where can I find this ID and where do I have to commit it to, because in the alter function there is no parameter to enter this id.

In the list _properties() method stands, that there is a prompt enabled but no ID.

**Comment by apiotrowskiMicroStrategy** [comment]
Hi @nxlsschxnk 

Can you show a code snippet you are using, so that I can see more context? And the error you get as well, for ease of reference.

**Comment by apiotrowskiMicroStrategy** [comment]
No further clarification or action requested, closing
