### ISSUE TITLE
Unable to get cube unless the cube has been published (post cubes/cubeid)

### ISSUE THREAD

**Issue by narquette** [MicroStrategy/mstrio-py#2]
In order for you to be able to pull up the dataset in the developer application is by publishing the cube after creating it using the post api for cubes/{cubeid}

**Comment by ssainz** [comment]
@narquette - In which version are you at? 10.11? Did you find cube in developer application after using the "microstrategy.create_dataset" call (uses datasets/ post api) ?

By default cubes created using create_dataset are saved in the user's personal report folder (My Reports).

**Comment by narquette** [comment]
We have version 11 installed in our dev environment.  The problem is that you can't use the cube to build a report in developer unless the cube has been published.

Thanks,

Nick

**Comment by narquette** [comment]
When I use the create dataset function demonstrated in the example, I'm not able to pull up the report in MyReports.

1) Message when clicking on report (cube has not been published) - https://www.screencast.com/t/jSXsSBvxjk

2) Message when I try to publish in the web

https://www.screencast.com/t/umFLHkeN

**Comment by ssainz** [comment]
@narquette  - Thanks for the screenshots. I could not reproduce the symptom:

1. Developer can create report based on "Employees" cube.  [http://www.screencast.com/t/IvYyaaNojC](http://www.screencast.com/t/IvYyaaNojC)
2. Web can create report based on "Employee" cube.  [http://www.screencast.com/t/5HRlBMn4R](http://www.screencast.com/t/5HRlBMn4R) 


Could you please confirm the version of your developer is "11.0.0048.0141"? [http://www.screencast.com/t/5fLy1bMNgCKW](http://www.screencast.com/t/5fLy1bMNgCKW)

Also, could you please take a screenshot of the cube monitor?

And, is the user that is creating the reports the same user that created the cube? Perhaps the user is different and does not have permissions to use/execute the cube.

**Comment by narquette** [comment]
You can close the issue. I was able to pull up the data. The issue was related to project clustering and making sure that accessing Microstrategy from the web was connected to the correct Intelligence server.
