### ISSUE TITLE
Can all objects be modified?

### ISSUE THREAD

**Issue by jonjones76** [MicroStrategy/mstrio-py#202]
It seems that not all objects can be modified, e.g. amend the description.  For example, I can easily change the description of an attribute by using the 'alter' method.  But the objects listed below don't have their own classes and subsequently an alter method to call

- Consolidation
- Custom Group
- Base Formula
- Prompts
- Derived Element
- Drill map 

Is there another way of amending these objects descriptions?

mstrio-py 11.4.6.101
Python 3.11.6

**Comment by AdamPiotrowski91** [comment]
Hi @jonjones76 

First of all, I can tell you that the goal is for all relevant MSTR objects to be supported by mstrio-py, but we are not there yet. We will be actively adding new modules so stay tuned!

If you have a specific need for a specific type more than the others, you can contact our MSTR TechSupport to create an Enhancement Request case. This will help us with prioritising and planning.

In the meantime, you can still use Python to alter those object, you will just need to make REST API requests directly as there are no modules (as you noticed) to do it for you. If a Library REST API exists, you can use it 😄 

Hope this helps and clarifies!

**Comment by apiotrowskiMicroStrategy** [comment]
Hi @jonjones76 

First of all, I can tell you that the goal is for all relevant MSTR objects to be supported by mstrio-py, but we are not there yet. We will be actively adding new modules so stay tuned!

If you have a specific need for a specific type more than the others, you can contact our MSTR TechSupport to create an Enhancement Request case. This will help us with prioritising and planning.

In the meantime, you can still use Python to alter those object, you will just need to make REST API requests directly as there are no modules (as you noticed) to do it for you. If a Library REST API exists, you can use it 😄

Hope this helps and clarifies!

---

Question answered. Request is a feature in nature and requires TechSupport case to apply. Closing.
