### ISSUE TITLE
mstrio-py 11.2 cube not defined

### ISSUE THREAD

**Issue by usechemario** [MicroStrategy/mstrio-py#25]
Hi,
I'm upgrading some application from mstrio-py 10.11 to 11.2 and I'm getting this error with 11.2:

![cube is not defined](https://user-images.githubusercontent.com/47214982/73773487-8a4f6100-4782-11ea-92ff-5858c7ee0435.png)

Do you guys see any reason for that?

Thanks,
Mario

**Comment by usechemario** [comment]
with capital C (as documented in your README.md), the issue is the same:

```python
my_cube = Cube(connection=conn, cube_id=cube_id)
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-57a75d0f22a3> in <module>
----> 1 my_cube = Cube(connection=conn, cube_id=cube_id)

NameError: name 'Cube' is not defined

**Comment by usechemario** [comment]
Hi there, I have just seen in the Workshop Book the complete sentence to be able to run the Cube method.

from mstrio.cube import Cube
my_cube = Cube(connection=conn, cube_id=cube_id)

This is working great. I would suggest to update the README.md.

Cheers, Mario

**Comment by drzamich** [comment]
@usechemario thanks for your suggestion. The Readme will be updated soon.
