### ISSUE TITLE
Update docstrings

### ISSUE THREAD

**Issue by BramVe** [MicroStrategy/mstrio-py#30]
Several docstrings are missing attribute definitions.

For example:
- reports/report_single_attribute_elements_coroutine missing offset, limit, session
- reports/report_single_attribute_elements missing offset, limit
- reports/report_instance missing body

**Comment by OskarDuda** [comment]
Hi @BramVe 
sorry for late reply - we're currently preparing a big documentation rework and will try to cover all the loose ends like this soon. Thanks a lot for the heads up, we'll look into this one for sure! :D

**Comment by urszulajaczewska** [comment]
Hi @BramVe I believe the problem is solved and currently docstrings don't miss any definitions.
