### ISSUE TITLE
Can't change projects

### ISSUE THREAD

**Issue by r3dunlop** [MicroStrategy/mstrio-py#35]
I am having a hard time changing projects with the same connection using the Connection class api. I found the way to do it was     `conn.session.headers['X-MSTR-ProjectID'] = project_id`. Is this intended? Is there a better way? I think this could be solved by making the `select_project` method accessible. Thanks!

**Comment by rodzyn022** [comment]
There is no better way at the moment, but `conn.session.headers['X-MSTR-ProjectID'] = project_id` should work. We are planning to make the select_project accessible in the near future. Thanks for sharing ;)

**Comment by BramVe** [comment]
@rodzyn022 are you willing to take a PR? Or is this already work in progress?

**Comment by rodzyn022** [comment]
@BramVe We are working on the product continuously, but we would be willing to go through your PR. Unfortunately, we cannot promise that we will accept it straight away.
