### ISSUE TITLE
cube instance id not being filled

### ISSUE THREAD

**Issue by r3dunlop** [MicroStrategy/mstrio-py#39]
It looks like the cube instance id is being found upon cube initialization but then stored in a local variable instead of in the attribute instance_id. Is this intended? The result is that the instance_id attribute is only filled if it is provided to the constructor upon creating a cube object. Does this mean that if I create a cube using cube.Cube(conn, cube_id) I won't have access to this cube instance if my cube object goes out of scope?

**Comment by OskarDuda** [comment]
Hi @r3dunlop thanks a lot for bringing this up! This looks like something we should give an extra look, since it might be a mistake on our side! We will keep you updated if anything changes in the subject!

**Comment by apiotrowskiMicroStrategy** [comment]
Issue have been resolved.
