### ISSUE TITLE
Any plan to add a github page for this repo?

### ISSUE THREAD

**Issue by XiaokunHou** [MicroStrategy/mstrio-py#43]
I like the python client. Do we plan to add a github page for this project?

So that there are some document for it.

**Comment by OskarDuda** [comment]
Hi @XiaokunHou ,
we are currently running a documentation website here http://www2.microstrategy.com/producthelp/Current/mstrio-py/ and you're more than welcome to take a look at it! :D This link is mentioned in our README.md file and is also available on our PyPI  page, if the URL was to be changed in the future you'll be able to find it there :)
