### ISSUE TITLE
Impossibility to import intelligent cube

### ISSUE THREAD

**Issue by LLejoly** [MicroStrategy/mstrio-py#46]
We are facing some problems to import an intelligent cube (previously generated by another python script) in our Python script. However, we do not have any problem to import reports and upload new Cubes on the Microstrategy platform.

We followed the procedure described on the repo to load a Cube but we have an error saying the Cube ID is not correct. We checked  the cube ID and this one is correct. 

The error message is the following one.

```
Error getting cube metadata information. Check Cube ID.
I-Server Error ERR001, (The data source (Cube Server) has not been initialized)
```

The code used is:

```
connection = Connection(url, usr_name, usr_password, project_id=project_id) <-- connection correctly established
my_cube = Cube(connection=connection, cube_id=cube_id)
my_cube = my_cube.to_dataframe
```

**Comment by LLejoly** [comment]
I tested the REST API with POSTMAN with the same parameters and it is working. Thus, the error is potentially in `Cube` class.

**Comment by LLejoly** [comment]
Hotfix proposed #47

**Comment by OskarDuda** [comment]
Hi @LLejoly ,
thanks for the heads up and double thanks for the proposed solution. We'll look into the issue and implement a fix ASAP! :D

**Comment by OskarDuda** [comment]
@LLejoly Could you please specify on which version of Microstrategy this issue occured?

**Comment by LLejoly** [comment]
Version impacted 11.3.0.2

**Comment by OskarDuda** [comment]
@LLejoly thanks for bringing this up! We've created an action item and will include a fix for this issue within our release plans.
