### ISSUE TITLE
Key error when trying establish a new connection

### ISSUE THREAD

**Issue by AndyNieubourg** [MicroStrategy/mstrio-py#49]
I'm receiving the following exception when creating a connection to MicroStrategy 2020 using the latest version of mstrio-py. My code is working for version 11.2.1.1 but not for 11.3.1.1 of the library. 

I provide url, username, password, projetname, login_mode=1, ssl_verify=False and certificate_path=None to create a new Connection object. 

File "/usr/local/lib/python3.6/site-packages/mstrio/connection.py", line 106, in __init__
    self.user_id = self.__get_user_info()['id']
    | KeyError: 'id'

**Comment by OskarDuda** [comment]
Hi @AndyNieubourg ,

thanks for the heads up. We've created a work item for this defect. Were you able to log in to Library on 11.3.1.1 with the specified user via browser? Could you please provide us with the list of installed libraries (including the mstrio-py) on your Python environment? In the terminal/cmd you can run `pip3 list` to get the list of installed libraries.
