### ISSUE TITLE
Where do you find table_name?

### ISSUE THREAD

**Issue by baiology** [MicroStrategy/mstrio-py#6]
Hi Scott,

where do you find table_name in mstr? Since we are inserting data to cube, table_name is not required can you please confirm.

thank you!

**Comment by scottrigney** [comment]
@baiology One way to access the table name is through MicroStrategy Web. Right-click on a dataset (cube icon), then select Edit. In the next screen, you'll see a list of attributes and metrics grouped by logical tables. The name at the top-left of the box (containing the attributes and metrics) is the table name.
