### ISSUE TITLE
Cannot import SuperCube 

### ISSUE THREAD

**Issue by JunhoKim01** [MicroStrategy/mstrio-py#62]
VERSION: 11.3.2.101

In example and documentation, 

`from mstrio.application_objects import SuperCube`

but this code does not work.

Instead, this works : 

`from mstrio.application_objects.datasets import SuperCube`

Is this a bug? or just minor mistakes in documentation & examples?

**Comment by urszulajaczewska** [comment]
This was fixed and will work as in examples from new release.
