### ISSUE TITLE
Cannot fetch bigger reports

### ISSUE THREAD

**Issue by pawelpopra** [MicroStrategy/mstrio-py#63]
Hello!
I am having issue with mstrio-py library when I downloaded it in my company - long story short I am able to connect to my company's microstrategy server - I can fetch small reports (<10 pages in MS), but when I try to fetch big reports (even 300 pages, where total in MS is around 77k) I receive an error.

Is it possible that my company blocks the connection after let's say few seconds, so that big reports cannot be fetch, or there could be another issue?

To be honest downloading data for report with 20 pages, should as well take 2s, not sure why my code only works for reports with around less 10 pages.

I am attaching my code and an error, thank you very much for help.

```
import urllib3
urllib3.disable_warnings()
from mstrio.connection import Connection
from mstrio.application_objects import Report
base_url = "deleted"
mstr_username = "deleted"
mstr_password = "deleted"
application_id = "deleted"
conn = Connection(base_url, mstr_username, mstr_password, application_id=application_id,ssl_verify=False)
report_id ='deleted'
my_report = Report(connection=conn, id=report_id, parallel=False)
my_report_df = my_report.to_dataframe()
print("Number of rows:")
print(my_report_df.shape[0])
print("print df")
print(my_report_df)
conn.close()
print("closed")
```
and error which I receive is:

```
Traceback (most recent call last):
  File "C:/Users/deleted", line 12, in <module>
    my_report_df = my_report.to_dataframe()
  File "P:\deleted\lib\site-packages\mstrio\application_objects\report.py", line 221, in to_dataframe
    if self.parallel and it_total > 1:
  File "P:\deleted\lib\site-packages\mstrio\utils\entity.py", line 534, in __getattribute__
    val = super(EntityBase, self).__getattribute__(name)
AttributeError: 'Report' object has no attribute 'parallel'
```

**Comment by Ander-MZ** [comment]
I had the same error, but I didn't know it was related to the size of the report until I read your post.

My **workaround** (not the best solution, I know, but it fixes the problem until they release an official fix) was to manually modify the **report.py** file, changing the following line:

`
Line 221:   if self.parallel and it_total > 1:
`
To
`
Line 221:   if it_total > 1:
`

**Comment by pawelpopra** [comment]
> I had the same error, but I didn't know it was related to the size of the report until I read your post.
> 
> My **workaround** (not the best solution, I know, but it fixes the problem until they release an official fix) was to manually modify the **report.py** file, changing the following line:
> 
> `Line 221: if self.parallel and it_total > 1:`
> To
> `Line 221: if it_total > 1:`

Hmm this unfortunately does not work for me :( how much rows are you extracting with the fix? Did you change anything else in mstrio-py, like limit in to_dataframe, or parallel=True/False?

**Comment by Ander-MZ** [comment]
I did a test extracting 9688 rows and everything worked well. If I can I will create a report with around 10K rows to see if it still works

**Comment by pawelpopra** [comment]
Unfortunately I am still having trouble with this, I am trying to download report with few million of rows and it only work if I do it part by part (100k each)
I do it over the loop by dateperiod, which gives me around 100k results in one go, but it is very time consuming...

**Comment by ignacyhologa** [comment]
Thanks for letting us know. Seems like a bug, expect a fix next release. 

Meanwhile try to set the missing parallel attribute manually:
```
my_report.parallel = False
```
before running the `to_dataframe()` method

**Comment by apiotrowskiMicroStrategy** [comment]
This has been fixed and new version of mstrio-py is available on PyPi as of today, and will be available here on github tomorrow.
