### ISSUE TITLE
Jupyter extensions are not loading in binderhub 

### ISSUE THREAD

**Issue by saratparameswar** [MicroStrategy/mstrio-py#68]
Hi,

I am trying to install the mstrio-py in the binderhub instance. As per their documentation, I tried different configuration files(requirement.txt, pipfile etc). ref: https://mybinder.readthedocs.io/en/latest/config_files.html
But mstrio jupyter plugin extensions static files are not loading. 

I also tried with dockerfile - still extension is not loading. Please see the dockerfile contents below.

FROM python:3.8-slim
RUN pip install --no-cache --upgrade pip && \
    pip install --no-cache notebook && \
    pip install --no-cache notebook jupyterlab && \
    pip install jupyter-client==7.0.2 && \
    pip install jupyter-contrib-core==0.3.3 && \
    pip install jupyter-contrib-nbextensions==0.5.1 && \
    pip install jupyter-core==4.7.1 && \
    pip install jupyter-highlight-selected-word==0.2.0 && \
    pip install jupyter-latex-envs==1.4.6 && \
    pip install jupyter-nbextensions-configurator==0.4.1 && \
    pip install jupyterlab-pygments==0.1.2 

RUN pip install --no-cache notebook jupyterlab
RUN pip install npm
RUN pip install ipywidgets
RUN pip install mstrio-py
RUN pip install jupyter_contrib_nbextensions
RUN jupyter contrib nbextension install --user

RUN jupyter nbextension install connector-jupyter --py --sys-prefix
RUN jupyter nbextension enable connector-jupyter --py --sys-prefix

ARG NB_USER=jovyan
ARG NB_UID=1000
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}

COPY . ${HOME}
USER root
RUN chown -R ${NB_UID} ${HOME}
USER ${NB_USER}

repo link: https://github.com/saratparameswar/minimal-dockerfile

Please help
<img width="569" alt="mstr-err-2" src="https://user-images.githubusercontent.com/7147190/133629626-1fe365d6-f98a-4bd0-9fa9-ef6bf01126af.PNG">
<img width="626" alt="mstr-err-3" src="https://user-images.githubusercontent.com/7147190/133629664-e7a1dbfa-abec-4fad-8b38-e9307484a820.PNG">
<img width="702" alt="mstr-err-1" src="https://user-images.githubusercontent.com/7147190/133629673-dc3a59fe-46ef-4424-9c1f-b6250b019aac.PNG">

Please help.

**Comment by saratparameswar** [comment]
I tried following repo too
https://gitlab.com/saratparameswar/jupyterwidget-in-binderhub
Static files are loading if the container is building and running outside binderhub - Tried in local machine. I can see widget without any issues.
In the binderhub, /hub is getting appended in the static URL. Any guess ?

**Comment by urszulajaczewska** [comment]
Hi @saratparameswar frontend is not supported in binderhub as well as in docker, mstrio-py backend should work fine.
