### ISSUE TITLE
How to check if the Cube is successfully re-published?

### ISSUE THREAD

**Issue by SamiRehmanNostra** [MicroStrategy/mstrio-py#69]
How can I check if a cube has been successfully refreshed, the status I receive if 17510 which means the processing of the cube is finished, but it doesn't tell me if the cube has refreshed or crashed?

```
while "Processing" in status:
    time.sleep(15)
    olap_cube_.refresh_status()
    print("refreshing status...")
    res = cubes.cube_info(connection=connection, id=cubeID)
    json_data = json.loads(res.text)
    cubes_infos=json_normalize(json_data, 'cubesInfos')
    print('cube {} is being published with status {}'.format(cube_id,cubes_infos.status[0] ))
    status=olap_cube_.show_status()
    if "Processing" not in status:
        print(olap_cube_._get_info())
        print("cube refreshed!")
        break
```

Please note I want to ensure that the cube has successfully been re-published.

**Comment by urszulajaczewska** [comment]
Hi @SamiRehmanNostra,

you can check cube state using following code:
```
from mstrio.project_objects.datasets.cube import CubeStates
CubeStates.show_status(17510)
```

The output in this case is:
`['Imported', 'Ready', 'Loaded', 'Persisted', 'Active', 'Reserved']`

All of the possible states are listed under **CubeState** class. If there would be any problem with cube, you will receive in the output **Dirty** or **Dirty Info** state.
