### ISSUE TITLE
Microstrategy widget is not loading when base-url is given

### ISSUE THREAD

**Issue by saratparameswar** [MicroStrategy/mstrio-py#71]
Hello Team,
I created a docker image using the Dockerfile in the following repository - [link to repository](https://gitlab.com/saratparameswar/jupyterwidget-in-binderhub/-/blob/main/Dockerfile)
I can see the jupyter widget  when I am launching the instance using the following docker command.

 **docker run -it --rm -p 8888:8888 venv_image_1 jupyter-lab --ip=0.0.0.0 --port=8888**

whenever I defines a base url, static files are not loading and widget is broken. See the command which causing the issue.

**docker run -it --rm -p 8888:8888 venv_image_1 jupyter-lab --ServerApp.base_url=/test-sarath --NotebookApp.base_url=/test-sarath-nbk --ip=0.0.0.0 --port=8888**

I assume, The base URL is causing the issue - The same issue happens when we try to launch a binderhub instance - because binderhub appends base-url. Please see the issue link which is already raised few days back [Issue-link](https://github.com/MicroStrategy/mstrio-py/issues/68)

Please help.

![console-log-1](https://user-images.githubusercontent.com/7147190/134902166-a7c27849-77c7-48a0-8c39-218c76ab9228.PNG)

**Comment by saratparameswar** [comment]
@apiotrowskiMicroStrategy  @scottrigney  Sorry to bother you. Could you please have a look :)

**Comment by urszulajaczewska** [comment]
Hi @saratparameswar, frontend in docker is not supported but mstrio-py backend should work fine.
