### ISSUE TITLE
Update numpy to 1.22.0

### ISSUE THREAD

**Issue by mFeigeInvia** [MicroStrategy/mstrio-py#76]
mstrio-py requiere explicit numpy==1.20.2 but current is 1.22.0 and most of the libs using/require new Versions than 1.20.2.

**Comment by urszulajaczewska** [comment]
Hi @mFeigeInvia, we'll look into it and I'll come back with an answer as soon as possible.

**Comment by urszulajaczewska** [comment]
@mFeigeInvia  We support numpy in versions `'numpy>=1.18.1, <1.22'`. In the requirements the version will be updated to 1.21.4 at the end of the month but you can overwrite it. If you want to use higher version than supported, you can update it manually but at your own risk.

**Comment by urszulajaczewska** [comment]
Hi @mFeigeInvia, in March release we've updated NumPy version. Currently it's `numpy==1.22.3` and supported versions are `numpy>=1.22.2, <1.23`.
