### ISSUE TITLE
Update example for user creation to read from csv or Excel.

### ISSUE THREAD

**Issue by ryanforsythe** [MicroStrategy/mstrio-py#80]
For a real world example is reading in a list of users with name, email, description from a CSV or Excel file.

Please adjust your example to include this scenario.

https://github.com/MicroStrategy/mstrio-py/blob/master/examples/user_mgmt.py

**Comment by urszulajaczewska** [comment]
Hi @ryanforsythe, we'll discuss this and I'll update you next week.

**Comment by urszulajaczewska** [comment]
Hi @ryanforsythe, we'll fix this and update will be available in March release.

**Comment by urszulajaczewska** [comment]
Hi @ryanforsythe, in March release we've updated `user_mgmt` example to reflect user creation from CSV file scenario.
