### ISSUE TITLE
Change cube publish to leverage V2 endpoint

### ISSUE THREAD

**Issue by justall** [MicroStrategy/mstrio-py#88]
Is it on the roadmap (or can it be added) to have mstrio-py/mstrio/api/cubes.py post to /api/v2/cubes/{cube_id} endpoint for cube publishing? Currently the post is to /api/cubes/{cube_id} which does not appear to return any data in the response beyond an HTTP status code. The v2 endpoint contains the corresponding JobId which is helpful for monitoring the job. I also can't find any information in the REST API Guide for the non-v2 endpoint. Would also need to update mstrio-py/mstrio/project_objects/datasets/olap_cube.py to read the post response as it does not currently.

Working around it in the meantime doing the Connection.post() myself but it would be nice to be able to just use the existing OlapCube.publish().

**Comment by urszulajaczewska** [comment]
Hi @justall, we'll review this change and let you know in case of any updates.
