### ISSUE TITLE
Extract a list of Active users and their email addresses 

### ISSUE THREAD

**Issue by EugenDra** [MicroStrategy/mstrio-py#89]
Hello,

Is it possible with mstrio to extract a list of all active users and their addresses from my Environment and export to an CSV or Excel file?

Many thanks!

**Comment by Dholmblad** [comment]
Hi @EugenDra Can you clarify what you mean by 'active user'? Does this mean users who do not have the 'disabled' property set?

**Comment by EugenDra** [comment]
Hi Darren, Yes

**Comment by Dholmblad** [comment]
@EugenDra Although the search engine does have parameters(EnumDSSXMLQuickSearchEnabledStatus) to search for:ALL, ENABLED_ONLY, for user objects. After reviewing the REST API implementation, this flag is only used on GET /collaboration/recipients which will return both users & usergroups. And not the GET /users API which is used by mstrio-py for UserManager functionality. 

We will need to add support for filtering on enabled users for GET /users API. 

Currently the only way to achieve this workflow would be to filter out the disabled users after retrival.

**Comment by urszulajaczewska** [comment]
Hi @EugenDra, we'll investigate GET /collaboration/recipients endpoint and update you with more info when we have it.
