### ISSUE TITLE
The date a user is added to a User Group

### ISSUE THREAD

**Issue by Daviesd8** [MicroStrategy/mstrio-py#92]
Would it be possible for the list_members() function available from a UserGroup object to also include the date when the User Object was added to the User Group 
This would allow for controlled access to User Groups for a period of time with automated scripting once that time period has been exceeded

**Comment by urszulajaczewska** [comment]
Hi @Daviesd8, we'll investigate this issue and available endpoints. I'll update you when we have more details

**Comment by urszulajaczewska** [comment]
Hi @Daviesd8, unfortunately it's not possible to include date. For `list_members` function we use `/api/usergroups/{id}/members` endpoint which returns list of users without any metadata when they were added to the group.
