### ISSUE TITLE
Report Connection Time Out

### ISSUE THREAD

**Issue by Charlie-Henry** [MicroStrategy/mstrio-py#97]
Hi there,

I am getting a similar issue to [this issue](https://github.com/MicroStrategy/mstrio-py/issues/55) where my report is timing out before being converted to a dataframe. It is about 30,000 records. After running `my_report.to_dataframe()` I get an error after five minutes, that my connection was timed out: 

```
ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

After, when I check my connection object `conn.status()`, I still get:
```
Connection to MicroStrategy Intelligence Server is active.
```

Is there a way to paginate through our report object? I see there is a `limit` parameter, but not a starting location. Or is there a way to increase the timeout of this connection?

Currently running mstrio-py == 11.3.6.102

My code is [here](https://github.com/cityofaustin/atd-prefect/blob/908549d170bdf4a6d086f203b456a7b9e750d814/flows/microstrategy/mstro_to_s3.py#L92)

**Comment by urszulajaczewska** [comment]
Hi @Charlie-Henry, we'll look into it and let you know when we gather more info.

**Comment by vioreldinu87** [comment]
Hi,

Your report is based on a MSI cube or you get data directly from a DB?

**Comment by Charlie-Henry** [comment]
@vioreldinu87 We are getting data from an external DB.

**Comment by vioreldinu87** [comment]
I ask you because if you say the conection to msi remains alive, maybe the connection is reseted in DB not in MSI.

I had a similar message but not with mstrio-py but with A script based on MSI SDK and the connection was dropped in DB.

**Comment by Charlie-Henry** [comment]
I have no issue running this report in the Microstrategy web app, still takes about 5 minutes but I don't get a timeout error?

**Comment by vioreldinu87** [comment]
Also you can check in dsserror.log from iserver to se if you have more details.

**Comment by urszulajaczewska** [comment]
Hi @Charlie-Henry, we'll work on this issue and fix should be available with the release of Report module.

**Comment by Charlie-Henry** [comment]
Great thanks @urszulajaczewska. We have a sort-of workaround in the meantime because it appears to cache the results and if I retry after ~10-15 minutes I can get `my_report.to_dataframe()` to run.

**Comment by urszulajaczewska** [comment]
@Charlie-Henry Report module has been moved to be released in Q3 of 2024, possibly earlier. We're sorry for the inconvenience and thank you for your patience.

**Comment by apiotrowskiMicroStrategy** [comment]
`Report` module released, no further action seem to be required
